set(CMAKE_BUILD_TYPE Release)
set(ANDROID 1)
set(CMAKE_CXX_FLAGS "-fexceptions")
set(CMAKE_CXX_FLAGS_DEBUG -fexceptions)
set(CMAKE_TOOLCHAIN_FILE android.toolchain.cmake)
set(ANDROID_STL stlport_static)
set(ANDROID_NDK /Users/jarlene/Library/Android/sdk/ndk-bundle)
set(ANDROID_TOOLCHAIN_NAME aarch64-linux-android-4.9)
set(ANDROID_ABI armeabi #[[armeabi-v7a arm64-v8a x86 x86_64 mips MIPS64]])
set(ANDROID_NATIVE_API_LEVEL android-24)
set(CPACK_PACKAGE_INSTALL_DIRECTORY "/libs")