set(THIRD_PARTY_PATH "${CMAKE_SOURCE_DIR}/third-party")
include(ExternalProject)
include(external/gtest)
include(external/gflags)
include(external/glog)
include(external/openmp)
include(external/blas)
include(external/eigen)
include(external/opencv)
include(external/llvm)