option(USE_TEST "use gtest" ON)
option(USE_GLOG "use glog" ON)
option(USE_GFLAGS "use gflags" ON)
option(USE_OPENMP "use openmp" ON)
option(USE_BLAS "use blas" OFF)
option(USE_MKL "use mkl" ON)
option(USE_EIGEN "use eigen" ON)
option(USE_OPENCV "use opencv" OFF)
option(USE_CUDA "use cuda" OFF)
option(USE_LLVM "use llvm" OFF)
option(USE_ZMQ "use zeromq" ON)

# platform
option(LINUX   "linux platform" OFF)
option(ANDROID "android platform" OFF)
option(IOS     "iso platform" OFF)
option(Windows "Windows platform" OFF)
option(OSX     "OSX platform" OFF)